# [Info]
# 左上角标题
site_name: Wu-wu-u's Notebooks
site_url: https://github.com/Wu-wu-u/Material-for-MkDocs-test
site_author: Wu-wu-u
repo_url: https://github.com/Wu-wu-u/Material-for-MkDocs-test
repo_name: Wu-wu-u/Notebooks
copyright: Copyright &copy; 2023-2024 <a herf="https://github.com/Wu-wu-u" target="_blank" rel="noopener">Wu-wu-u</a>

theme:
  name: material
  language: zh # 语言设置为中文(会改变搜索栏/最后修改 等文字)，默认为英文
  #logo: assets/logo.jpg # 页面中顶部栏左侧图标
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github # git-alt/github-alt
    logo: material/notebook-outline
  font: False
  palette:
    # 日间模式
    - media: "(prefers-color-scheme: light)"
      scheme: default

      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: white

      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      # accent: teal
        
      toggle:
        # 图标
        icon: material/weather-sunny
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs

    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top

    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes

    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand

    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy

    # 可以在代码块中内嵌注释
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations
    - content.code.annotate

    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest

    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Wu-wu-u

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - css/custom.css 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
